name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Testing Environment
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: Create .env file for proxy server
      working-directory: ./Server
      run: |
        echo "FINNHUB_API_KEY=${{ secrets.API_KEY }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
    - name: Starts stack
      run: docker compose up -d --build
    - name: Waits for proxy server to retrieve info
      run: sleep 70
    - name: Install Playwright dependencies
      working-directory: ./WebAppTests
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./WebAppTests
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./WebAppTests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ./WebAppTests
        retention-days: 30
