name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: ${{ matrix.node-version }}
    - name: Set up proxy server packages
      working-directory: ./Server
      run: npm ci
    - name: Builds proxy server
      working-directory: ./Server
      run: npm run build
    - name: Create .env file for proxy server
      working-directory: ./Server
      run: |
        echo "FINNHUB_API_KEY=${{ secrets.API_KEY }}" >> .env
        echo "" >> .env
        echo "PORT=${{secrets.PORT}}" >> .env
    - name: Starts proxy server
      working-directory: ./Server
      run: npm run start &
    - name: Waits for proxy server to retrieve info
      run: sleep 70
    - name: Set up web display
      working-directory: ./NasdaqDisplay
      run: npm ci
    - name: Build web display
      working-directory: ./NasdaqDisplay
      run: npm run build
    - name: Start web display
      working-directory: ./NasdaqDisplay
      run: npm run preview &
    - name: Install Playwright dependencies
      working-directory: ./WebAppTests
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./WebAppTests
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./WebAppTests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
